//console.log(turnstile.data.page_view ? 'selector 1 : ' +  turnstile.data.page_view.module_selectors[0].state : null)
//console.log(turnstile.data.page_view ? 'selector 2 : ' +  turnstile.data.page_view.module_selectors[1].state : null)
//console.log(turnstile.data.page_view ? 'selector 3 : ' +  turnstile.data.page_view.module_selectors[2].state : null)
//console.log(turnstile.data.page_view ? 'selector 4 : ' +  turnstile.data.page_view.module_selectors[3].state : null)
//console.log(turnstile.data.page_view ? 'selector 5 : ' +  turnstile.data.page_view.module_selectors[4].state : null)
//console.log(turnstile.data.page_view ? 'selector 6 : ' +  turnstile.data.page_view.module_selectors[5].state : null)
//console.log(turnstile.data.page_view ? 'selector 7 : ' +  turnstile.data.page_view.module_selectors[6].state : null)
//console.log(turnstile.data.page_view ? 'selector 8 : ' +  turnstile.data.page_view.module_selectors[7].state : null)
//console.log('====================================================')
//console.log('STATE 1 : ' +  this.state.selectOne)
//console.log('STATE 2 : ' +  this.state.selectTwo)
//console.log('STATE 3 : ' +  this.state.selectThree)
//console.log('STATE 4 : ' +  this.state.selectFour)
//console.log('STATE 5 : ' +  this.state.selectFive)
//console.log('STATE 6 : ' +  this.state.selectSix)
//console.log('STATE 7 : ' +  this.state.selectSeven)
//console.log('STATE 8 : ' +  this.state.selectEight)
//console.log('====================================================');
