export const FETCHING_DATA_BARRIER_REQUEST = 'FETCHING_DATA_BARRIER_REQUEST';
export const FETCHING_DATA_BARRIER_SUCCESS = 'FETCHING_DATA_BARRIER_SUCCESS';
export const FETCHING_DATA_BARRIER_FAILURE = 'FETCHING_DATA_BARRIER_FAILURE';
export const TOGGLE_MODAL_BARRIER = 'TOGGLE_MODAL_BARRIER';
export const TOGGLE_MODAL_BARRIER_MAIN_INFO = 'TOGGLE_MODAL_BARRIER_MAIN_INFO';